{
  "comments": [
    {
      "key": {
        "uuid": "3015e588_32dc1417",
        "filename": "src/erase/erase.cpp",
        "patchSetId": 36
      },
      "lineNbr": 19,
      "author": {
        "id": 1000188
      },
      "writtenOn": "2021-12-08T11:09:42Z",
      "side": 1,
      "message": "Same here, stdplus::fd::open throws and exception automatically. You might want to try { } catch if you need specific errors to be propagated upstack and have log output printed.",
      "revId": "4c7048e6b932fc6f99c0cd036e53eed0cc969156",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6b299b9c_7bbd6b39",
        "filename": "src/erase/erase.cpp",
        "patchSetId": 36
      },
      "lineNbr": 19,
      "author": {
        "id": 1000593
      },
      "writtenOn": "2021-12-08T20:26:01Z",
      "side": 1,
      "message": "sounds good, I added try and catch, and would like to propagate errors up to the dbus interface error.",
      "parentUuid": "3015e588_32dc1417",
      "revId": "4c7048e6b932fc6f99c0cd036e53eed0cc969156",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": false
    }
  ]
}